//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignNow.Net.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SignNow.Net.Exceptions.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed ranges must be from 15 to 45 minutes.
        /// </summary>
        internal static string AllowedRangeMustBeFrom15to45 {
            get {
                return ResourceManager.GetString("AllowedRangeMustBeFrom15to45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot assign the `{0}` role to the user. The document must contain fields with the `{0}` role before assigning it to users..
        /// </summary>
        internal static string CannotAddRole {
            get {
                return ResourceManager.GetString("CannotAddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document does not contain Roles..
        /// </summary>
        internal static string DocumentDoesNotHaveRoles {
            get {
                return ResourceManager.GetString("DocumentDoesNotHaveRoles", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This document group does not contains any document..
        /// </summary>
        internal static string DocumentGroupWithoutDocs {
            get {
                return ResourceManager.GetString("DocumentGroupWithoutDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format of email `{0}`. The required format: valid email address (e.g john+1@gmail.com or john123@gmail.com)..
        /// </summary>
        internal static string InvalidFormatOfEmail {
            get {
                return ResourceManager.GetString("InvalidFormatOfEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format of ID `{0}`. The required format: 40 characters long, case-sensitive, letters and numbers, underscore allowed..
        /// </summary>
        internal static string InvalidFormatOfId {
            get {
                return ResourceManager.GetString("InvalidFormatOfId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Json syntax in response.
        /// </summary>
        internal static string InvalidJsonSyntax {
            get {
                return ResourceManager.GetString("InvalidJsonSyntax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invite already exists for this document..
        /// </summary>
        internal static string InviteIsAlreadyExistsForDocument {
            get {
                return ResourceManager.GetString("InviteIsAlreadyExistsForDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document must contains at least one fillable field assigned to one role..
        /// </summary>
        internal static string NoFillableFieldsWithRole {
            get {
                return ResourceManager.GetString("NoFillableFieldsWithRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestUrl cannot be empty or null.
        /// </summary>
        internal static string RequestUrlIsNull {
            get {
                return ResourceManager.GetString("RequestUrlIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot be null, empty or whitespace.
        /// </summary>
        internal static string StringNotNullOrEmptyOrWhitespace {
            get {
                return ResourceManager.GetString("StringNotNullOrEmptyOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process request {0}:{1}, Time taken: {2}s.
        /// </summary>
        internal static string UnableToProcessRequest {
            get {
                return ResourceManager.GetString("UnableToProcessRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected value when converting to `{0}`. Expected {1}, got {2}..
        /// </summary>
        internal static string UnexpectedValueWhenConverting {
            get {
                return ResourceManager.GetString("UnexpectedValueWhenConverting", resourceCulture);
            }
        }
    }
}
